export const countries = [
    { name: "United States", capital: "Washington, D.C.", population: 331002651, cities: ["New York", "Los Angeles", "Chicago"] },
    { name: "Canada", capital: "Ottawa", population: 37742154, cities: ["Toronto", "Vancouver", "Montreal"] },
    { name: "United Kingdom", capital: "London", population: 67886011, cities: ["London", "Birmingham", "Manchester"] },
    { name: "Australia", capital: "Canberra", population: 25499884, cities: ["Sydney", "Melbourne", "Brisbane"] },
    { name: "Germany", capital: "Berlin", population: 83783942, cities: ["Berlin", "Munich", "Frankfurt"] },
    { name: "France", capital: "Paris", population: 65273511, cities: ["Paris", "Marseille", "Lyon"] },
    { name: "Japan", capital: "Tokyo", population: 126476461, cities: ["Tokyo", "Osaka", "Kyoto"] },
    { name: "India", capital: "New Delhi", population: 1380004385, cities: ["Mumbai", "Delhi", "Bangalore"] },
    { name: "Brazil", capital: "Brasília", population: 212559417, cities: ["São Paulo", "Rio de Janeiro", "Salvador"] },
    { name: "Italy", capital: "Rome", population: 60244639, cities: ["Rome", "Milan", "Naples"] },
    { name: "Spain", capital: "Madrid", population: 46754778, cities: ["Madrid", "Barcelona", "Valencia"] },
    { name: "Mexico", capital: "Mexico City", population: 128932753, cities: ["Mexico City", "Guadalajara", "Monterrey"] },
    { name: "Russia", capital: "Moscow", population: 145912025, cities: ["Moscow", "Saint Petersburg", "Novosibirsk"] },
    { name: "South Korea", capital: "Seoul", population: 51269185, cities: ["Seoul", "Busan", "Incheon"] },
    { name: "Netherlands", capital: "Amsterdam", population: 17134872, cities: ["Amsterdam", "Rotterdam", "The Hague"] },
    { name: "Turkey", capital: "Ankara", population: 84339067, cities: ["Istanbul", "Ankara", "Izmir"] },
    { name: "Saudi Arabia", capital: "Riyadh", population: 34813871, cities: ["Riyadh", "Jeddah", "Mecca"] },
    { name: "Sweden", capital: "Stockholm", population: 10099265, cities: ["Stockholm", "Gothenburg", "Malmo"] },
    { name: "Norway", capital: "Oslo", population: 5421241, cities: ["Oslo", "Bergen", "Stavanger"] },
    { name: "Switzerland", capital: "Bern", population: 8654622, cities: ["Zurich", "Geneva", "Basel"] },
    { name: "Belgium", capital: "Brussels", population: 11589623, cities: ["Brussels", "Antwerp", "Ghent"] },
    { name: "Austria", capital: "Vienna", population: 8917205, cities: ["Vienna", "Graz", "Salzburg"] },
    { name: "Finland", capital: "Helsinki", population: 5540720, cities: ["Helsinki", "Espoo", "Tampere"] },
    { name: "Denmark", capital: "Copenhagen", population: 5818553, cities: ["Copenhagen", "Aarhus", "Odense"] },
    { name: "Ireland", capital: "Dublin", population: 4937786, cities: ["Dublin", "Cork", "Limerick"] },
    { name: "New Zealand", capital: "Wellington", population: 4822233, cities: ["Auckland", "Wellington", "Christchurch"] },
    { name: "Singapore", capital: "Singapore", population: 5850342, cities: ["Singapore"] },
    { name: "South Africa", capital: "Pretoria", population: 59308690, cities: ["Johannesburg", "Cape Town", "Durban"] },
    { name: "Argentina", capital: "Buenos Aires", population: 45195777, cities: ["Buenos Aires", "Córdoba", "Rosario"] },
    { name: "Chile", capital: "Santiago", population: 19116201, cities: ["Santiago", "Valparaíso", "Concepción"] },
    { name: "Colombia", capital: "Bogotá", population: 50882891, cities: ["Bogotá", "Medellín", "Cali"] },
    { name: "Peru", capital: "Lima", population: 32971854, cities: ["Lima", "Arequipa", "Trujillo"] },
    { name: "Philippines", capital: "Manila", population: 109581078, cities: ["Manila", "Cebu", "Davao"] },
    { name: "Vietnam", capital: "Hanoi", population: 97338579, cities: ["Hanoi", "Ho Chi Minh City", "Da Nang"] },
    { name: "Thailand", capital: "Bangkok", population: 69799978, cities: ["Bangkok", "Chiang Mai", "Phuket"] },
    { name: "Malaysia", capital: "Kuala Lumpur", population: 32365999, cities: ["Kuala Lumpur", "George Town", "Johor Bahru"] },
    { name: "Egypt", capital: "Cairo", population: 102334155, cities: ["Cairo", "Alexandria", "Giza"] },
    { name: "Iraq", capital: "Baghdad", population: 40222493, cities: ["Baghdad", "Basra", "Mosul"] },
    { name: "Iran", capital: "Tehran", population: 83992949, cities: ["Tehran", "Isfahan", "Shiraz"] },
    { name: "Ukraine", capital: "Kyiv", population: 43733762, cities: ["Kyiv", "Kharkiv", "Odesa"] },
    { name: "Czech Republic", capital: "Prague", population: 10708981, cities: ["Prague", "Brno", "Ostrava"] },
    { name: "Portugal", capital: "Lisbon", population: 10196709, cities: ["Lisbon", "Porto", "Amadora"] },
    { name: "Hungary", capital: "Budapest", population: 9660351, cities: ["Budapest", "Debrecen", "Szeged"] },
    { name: "Romania", capital: "Bucharest", population: 19237691, cities: ["Bucharest", "Cluj-Napoca", "Timișoara"] },
    { name: "Slovakia", capital: "Bratislava", population: 5456362, cities: ["Bratislava", "Košice", "Prešov"] },
    { name: "Croatia", capital: "Zagreb", population: 4105267, cities: ["Zagreb", "Split", "Rijeka"] },
    { name: "Bulgaria", capital: "Sofia", population: 6948445, cities: ["Sofia", "Plovdiv", "Varna"] },
    { name: "Serbia", capital: "Belgrade", population: 8772235, cities: ["Belgrade", "Novi Sad", "Niš"] },
    { name: "Lithuania", capital: "Vilnius", population: 2722289, cities: ["Vilnius", "Kaunas", "Klaipėda"] },
    { name: "Latvia", capital: "Riga", population: 1886198, cities: ["Riga", "Daugavpils", "Liepāja"] },
    { name: "Estonia", capital: "Tallinn", population: 1326535, cities: ["Tallinn", "Tartu", "Narva"] },
    { name: "Moldova", capital: "Chișinău", population: 2657637, cities: ["Chișinău", "Bălți", "Bender"] },
    { name: "Georgia", capital: "Tbilisi", population: 3989167, cities: ["Tbilisi", "Batumi", "Kutaisi"] },
    { name: "Armenia", capital: "Yerevan", population: 2963243, cities: ["Yerevan", "Gyumri", "Vagharshapat"] },
    { name: "Azerbaijan", capital: "Baku", population: 10139177, cities: ["Baku", "Ganja", "Lankaran"] },
    { name: "Kazakhstan", capital: "Nur-Sultan", population: 18776707, cities: ["Almaty", "Nur-Sultan", "Shymkent"] },
    { name: "Uzbekistan", capital: "Tashkent", population: 33469199, cities: ["Tashkent", "Samarkand", "Bukhara"] },
    { name: "Kyrgyzstan", capital: "Bishkek", population: 6524195, cities: ["Bishkek", "Osh", "Jalal-Abad"] },
    { name: "Tajikistan", capital: "Dushanbe", population: 9537645, cities: ["Dushanbe", "Khujand", "Kulob"] },
    { name: "Turkmenistan", capital: "Ashgabat", population: 5942088, cities: ["Ashgabat", "Turkmenabat", "Mary"] },
    { name: "Malta", capital: "Valletta", population: 514999, cities: ["Valletta", "Birkirkara", "Sliema"] },
    { name: "Iceland", capital: "Reykjavik", population: 366418, cities: ["Reykjavik", "Kopavogur", "Hafnarfjordur"] },
    { name: "Luxembourg", capital: "Luxembourg City", population: 634814, cities: ["Luxembourg City", "Esch-sur-Alzette", "Differdange"] },
    { name: "Monaco", capital: "Monaco", population: 39242, cities: ["Monaco"] },
    { name: "San Marino", capital: "San Marino", population: 33931, cities: ["San Marino"] },
    { name: "Andorra", capital: "Andorra la Vella", population: 77265, cities: ["Andorra la Vella"] },
    { name: "Vatican City", capital: "Vatican City", population: 801, cities: ["Vatican City"] },
    { name: "Bangladesh", capital: "Dhaka", population: 166303498, cities: ["Dhaka", "Chittagong", "Khulna"] },
    { name: "Nepal", capital: "Kathmandu", population: 29136808, cities: ["Kathmandu", "Pokhara", "Lalitpur"] },
    { name: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", population: 21413249, cities: ["Colombo", "Kandy", "Galle"] },
    { name: "Myanmar", capital: "Naypyidaw", population: 54409794, cities: ["Yangon", "Mandalay", "Naypyidaw"] },
    { name: "Afghanistan", capital: "Kabul", population: 38928346, cities: ["Kabul", "Kandahar", "Herat"] },
    { name: "Kazakhstan", capital: "Nur-Sultan", population: 18776707, cities: ["Almaty", "Nur-Sultan", "Shymkent"] },
    { name: "Jordan", capital: "Amman", population: 10203134, cities: ["Amman", "Zarqa", "Irbid"] },
    { name: "Lebanon", capital: "Beirut", population: 6825445, cities: ["Beirut", "Tripoli", "Sidon"] },
    { name: "Syria", capital: "Damascus", population: 17500657, cities: ["Damascus", "Aleppo", "Homs"] },
    { name: "Oman", capital: "Muscat", population: 5106626, cities: ["Muscat", "Salalah", "Sohar"] },
    { name: "Qatar", capital: "Doha", population: 2881060, cities: ["Doha", "Al Rayyan", "Al Wakrah"] },
    { name: "Bahrain", capital: "Manama", population: 1701575, cities: ["Manama", "Muharraq", "Riffa"] },
    { name: "Kuwait", capital: "Kuwait City", population: 4270563, cities: ["Kuwait City", "Hawalli", "Salmiya"] },
    { name: "United Arab Emirates", capital: "Abu Dhabi", population: 9890402, cities: ["Dubai", "Abu Dhabi", "Sharjah"] },
    { name: "Malawi", capital: "Lilongwe", population: 19129952, cities: ["Lilongwe", "Blantyre", "Mzuzu"] },
    { name: "Zambia", capital: "Lusaka", population: 18383955, cities: ["Lusaka", "Ndola", "Kitwe"] },
    { name: "Zimbabwe", capital: "Harare", population: 14862924, cities: ["Harare", "Bulawayo", "Gweru"] },
    { name: "Tanzania", capital: "Dodoma", population: 59734218, cities: ["Dar es Salaam", "Dodoma", "Arusha"] },
    { name: "Kenya", capital: "Nairobi", population: 53771296, cities: ["Nairobi", "Mombasa", "Nakuru"] },
    { name: "Uganda", capital: "Kampala", population: 45741007, cities: ["Kampala", "Entebbe", "Gulu"] },
    { name: "Rwanda", capital: "Kigali", population: 12952218, cities: ["Kigali", "Butare", "Gisenyi"] },
    { name: "Burundi", capital: "Gitega", population: 11890784, cities: ["Gitega", "Bujumbura", "Ngozi"] },
    { name: "South Sudan", capital: "Juba", population: 10919573, cities: ["Juba", "Wau", "Malakal"] },
    { name: "Somalia", capital: "Mogadishu", population: 15893222, cities: ["Mogadishu", "Hargeisa", "Kismayo"] },
    { name: "Djibouti", capital: "Djibouti", population: 883560, cities: ["Djibouti", "Ali Sabieh", "Tadjourah"] },
    { name: "Eritrea", capital: "Asmara", population: 3546000, cities: ["Asmara", "Keren", "Massawa"] },
    { name: "Comoros", capital: "Moroni", population: 806153, cities: ["Moroni", "Moutsamoudou", "Mitsamiouli"] },
    { name: "Seychelles", capital: "Victoria", population: 98347, cities: ["Victoria", "Anse Boileau", "Beau Vallon"] },
    { name: "Mauritius", capital: "Port Louis", population: 1271768, cities: ["Port Louis", "Curepipe", "Vacoas"] },
    { name: "Cape Verde", capital: "Praia", population: 543767, cities: ["Praia", "Mindelo", "Santa Maria"] },
    { name: "Gambia", capital: "Banjul", population: 2416661, cities: ["Banjul", "Serrekunda", "Brikama"] },
    { name: "Senegal", capital: "Dakar", population: 16425864, cities: ["Dakar", "Touba", "Saint-Louis"] },
    { name: "Mali", capital: "Bamako", population: 20250833, cities: ["Bamako", "Sikasso", "Mopti"] },
    { name: "Niger", capital: "Niamey", population: 24206644, cities: ["Niamey", "Zinder", "Maradi"] },
    { name: "Chad", capital: "N'Djamena", population: 14497000, cities: ["N'Djamena", "Moundou", "Sarh"] },
    { name: "Central African Republic", capital: "Bangui", population: 5496064, cities: ["Bangui", "Bimbo", "Berbérati"] },
    { name: "Congo, Republic of the", capital: "Brazzaville", population: 5500000, cities: ["Brazzaville", "Pointe-Noire", "Dolisie"] },
    { name: "Congo, Democratic Republic of the", capital: "Kinshasa", population: 89561403, cities: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi"] },
    { name: "Equatorial Guinea", capital: "Malabo", population: 1402985, cities: ["Malabo", "Bata", "Ebebiyin"] },
    { name: "Sao Tome and Principe", capital: "São Tomé", population: 219159, cities: ["São Tomé", "Principe", "Neves"] },
    { name: "Lesotho", capital: "Maseru", population: 2142249, cities: ["Maseru", "Teyateyaneng", "Maputsoe"] },
    { name: "Eswatini", capital: "Mbabane", population: 1160164, cities: ["Mbabane", "Manzini", "Lobamba"] },
    { name: "Botswana", capital: "Gaborone", population: 2141206, cities: ["Gaborone", "Francistown", "Molepolole"] },
    { name: "Namibia", capital: "Windhoek", population: 2540905, cities: ["Windhoek", "Swakopmund", "Walvis Bay"] },
    { name: "Angola", capital: "Luanda", population: 32866272, cities: ["Luanda", "N'dalatando", "Huambo"] },
    { name: "Mozambique", capital: "Maputo", population: 31255435, cities: ["Maputo", "Beira", "Nampula"] },
    { name: "Togo", capital: "Lomé", population: 8278724, cities: ["Lomé", "Sokodé", "Kara"] },
    { name: "Benin", capital: "Porto-Novo", population: 12123200, cities: ["Cotonou", "Porto-Novo", "Parakou"] },
    { name: "Burkina Faso", capital: "Ouagadougou", population: 20511624, cities: ["Ouagadougou", "Bobo-Dioulasso", "Koudougou"] },
    { name: "Ivory Coast", capital: "Yamoussoukro", population: 26378000, cities: ["Abidjan", "Bouaké", "San Pedro"] },
    { name: "Ghana", capital: "Accra", population: 31072940, cities: ["Accra", "Kumasi", "Tamale"] },
    { name: "Nigeria", capital: "Abuja", population: 206139589, cities: ["Lagos", "Abuja", "Port Harcourt"] },
    { name: "Sierra Leone", capital: "Freetown", population: 7976985, cities: ["Freetown", "Bo", "Kenema"] },
    { name: "Liberia", capital: "Monrovia", population: 5057681, cities: ["Monrovia", "Gbarnga", "Buchanan"] },
    { name: "Tanzania", capital: "Dodoma", population: 59734218, cities: ["Dar es Salaam", "Dodoma", "Arusha"] },
    { name: "Somalia", capital: "Mogadishu", population: 15893222, cities: ["Mogadishu", "Hargeisa", "Kismayo"] },
    { name: "Malawi", capital: "Lilongwe", population: 19129952, cities: ["Lilongwe", "Blantyre", "Mzuzu"] },
    { name: "Zambia", capital: "Lusaka", population: 18383955, cities: ["Lusaka", "Ndola", "Kitwe"] },
    { name: "Zimbabwe", capital: "Harare", population: 14862924, cities: ["Harare", "Bulawayo", "Gweru"] },
    { name: "South Africa", capital: "Pretoria", population: 59308690, cities: ["Johannesburg", "Cape Town", "Durban"] },
    { name: "Lesotho", capital: "Maseru", population: 2142249, cities: ["Maseru", "Teyateyaneng", "Maputsoe"] },
    { name: "Eswatini", capital: "Mbabane", population: 1160164, cities: ["Mbabane", "Manzini", "Lobamba"] },
    { name: "Botswana", capital: "Gaborone", population: 2141206, cities: ["Gaborone", "Francistown", "Molepolole"] },
    { name: "Namibia", capital: "Windhoek", population: 2540905, cities: ["Windhoek", "Swakopmund", "Walvis Bay"] },
    { name: "Angola", capital: "Luanda", population: 32866272, cities: ["Luanda", "N'dalatando", "Huambo"] },
    { name: "Mozambique", capital: "Maputo", population: 31255435, cities: ["Maputo", "Beira", "Nampula"] },
    { name: "Togo", capital: "Lomé", population: 8278724, cities: ["Lomé", "Sokodé", "Kara"] },
    { name: "Benin", capital: "Porto-Novo", population: 12123200, cities: ["Cotonou", "Porto-Novo", "Parakou"] },
    { name: "Burkina Faso", capital: "Ouagadougou", population: 20511624, cities: ["Ouagadougou", "Bobo-Dioulasso", "Koudougou"] },
    { name: "Ivory Coast", capital: "Yamoussoukro", population: 26378000, cities: ["Abidjan", "Bouaké", "San Pedro"] },
    { name: "Ghana", capital: "Accra", population: 31072940, cities: ["Accra", "Kumasi", "Tamale"] },
    { name: "Nigeria", capital: "Abuja", population: 206139589, cities: ["Lagos", "Abuja", "Port Harcourt"] },
    { name: "Sierra Leone", capital: "Freetown", population: 7976985, cities: ["Freetown", "Bo", "Kenema"] },
    { name: "Liberia", capital: "Monrovia", population: 5057681, cities: ["Monrovia", "Gbarnga", "Buchanan"] },
    { name: "Gambia", capital: "Banjul", population: 2416661, cities: ["Banjul", "Serrekunda", "Brikama"] },
    { name: "Senegal", capital: "Dakar", population: 16425864, cities: ["Dakar", "Touba", "Saint-Louis"] },
    { name: "Mali", capital: "Bamako", population: 20250833, cities: ["Bamako", "Sikasso", "Mopti"] },
    { name: "Niger", capital: "Niamey", population: 24206644, cities: ["Niamey", "Zinder", "Maradi"] },
    { name: "Chad", capital: "N'Djamena", population: 14497000, cities: ["N'Djamena", "Moundou", "Sarh"] },
    { name: "Central African Republic", capital: "Bangui", population: 5496064, cities: ["Bangui", "Bimbo", "Berbérati"] },
    { name: "Congo, Republic of the", capital: "Brazzaville", population: 5500000, cities: ["Brazzaville", "Pointe-Noire", "Dolisie"] },
    { name: "Congo, Democratic Republic of the", capital: "Kinshasa", population: 89561403, cities: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi"] },
    { name: "Equatorial Guinea", capital: "Malabo", population: 1402985, cities: ["Malabo", "Bata", "Ebebiyin"] },
    { name: "Sao Tome and Principe", capital: "São Tomé", population: 219159, cities: ["São Tomé", "Principe", "Neves"] },
    { name: "Malawi", capital: "Lilongwe", population: 19129952, cities: ["Lilongwe", "Blantyre", "Mzuzu"] },
    { name: "Zambia", capital: "Lusaka", population: 18383955, cities: ["Lusaka", "Ndola", "Kitwe"] },
    { name: "Zimbabwe", capital: "Harare", population: 14862924, cities: ["Harare", "Bulawayo", "Gweru"] },
    { name: "Tanzania", capital: "Dodoma", population: 59734218, cities: ["Dar es Salaam", "Dodoma", "Arusha"] },
    { name: "Kenya", capital: "Nairobi", population: 53771296, cities: ["Nairobi", "Mombasa", "Nakuru"] },
    { name: "Uganda", capital: "Kampala", population: 45741007, cities: ["Kampala", "Entebbe", "Gulu"] },
    { name: "Rwanda", capital: "Kigali", population: 12952218, cities: ["Kigali", "Butare", "Gisenyi"] },
    { name: "Burundi", capital: "Gitega", population: 11890784, cities: ["Gitega", "Bujumbura", "Ngozi"] },
    { name: "South Sudan", capital: "Juba", population: 10919573, cities: ["Juba", "Wau", "Malakal"] },
    { name: "Somalia", capital: "Mogadishu", population: 15893222, cities: ["Mogadishu", "Hargeisa", "Kismayo"] },
    { name: "Djibouti", capital: "Djibouti", population: 883560, cities: ["Djibouti", "Ali Sabieh", "Tadjourah"] },
    { name: "Eritrea", capital: "Asmara", population: 3546000, cities: ["Asmara", "Keren", "Massawa"] },
    { name: "Comoros", capital: "Moroni", population: 806153, cities: ["Moroni", "Moutsamoudou", "Mitsamiouli"] },
    { name: "Seychelles", capital: "Victoria", population: 98347, cities: ["Victoria", "Anse Boileau", "Beau Vallon"] },
    { name: "Mauritius", capital: "Port Louis", population: 1271768, cities: ["Port Louis", "Curepipe", "Vacoas"] },
    { name: "Cape Verde", capital: "Praia", population: 543767, cities: ["Praia", "Mindelo", "Santa Maria"] },
    { name: "Gambia", capital: "Banjul", population: 2416661, cities: ["Banjul", "Serrekunda", "Brikama"] },
    { name: "Senegal", capital: "Dakar", population: 16425864, cities: ["Dakar", "Touba", "Saint-Louis"] },
    { name: "Mali", capital: "Bamako", population: 20250833, cities: ["Bamako", "Sikasso", "Mopti"] },
    { name: "Niger", capital: "Niamey", population: 24206644, cities: ["Niamey", "Zinder", "Maradi"] },
    { name: "Chad", capital: "N'Djamena", population: 14497000, cities: ["N'Djamena", "Moundou", "Sarh"] },
    { name: "Central African Republic", capital: "Bangui", population: 5496064, cities: ["Bangui", "Bimbo", "Berbérati"] },
    { name: "Cameroon", capital: "Yaoundé", population: 22709892, cities: ["Yaoundé", "Douala", "Garoua"] },
    { name: "Congo, Republic of the", capital: "Brazzaville", population: 5500000, cities: ["Brazzaville", "Pointe-Noire", "Dolisie"] },
    { name: "Congo, Democratic Republic of the", capital: "Kinshasa", population: 89561403, cities: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi"] },
    { name: "Equatorial Guinea", capital: "Malabo", population: 1402985, cities: ["Malabo", "Bata", "Ebebiyin"] },
    { name: "Sao Tome and Principe", capital: "São Tomé", population: 219159, cities: ["São Tomé", "Principe", "Neves"] },
    { name: "Malawi", capital: "Lilongwe", population: 19129952, cities: ["Lilongwe", "Blantyre", "Mzuzu"] },
    { name: "Zambia", capital: "Lusaka", population: 18383955, cities: ["Lusaka", "Ndola", "Kitwe"] },
    { name: "Zimbabwe", capital: "Harare", population: 14862924, cities: ["Harare", "Bulawayo", "Gweru"] },
    { name: "Tanzania", capital: "Dodoma", population: 59734218, cities: ["Dar es Salaam", "Dodoma", "Arusha"] },
    { name: "Kenya", capital: "Nairobi", population: 53771296, cities: ["Nairobi", "Mombasa", "Nakuru"] },
    { name: "Uganda", capital: "Kampala", population: 45741007, cities: ["Kampala", "Entebbe", "Gulu"] },
    { name: "Rwanda", capital: "Kigali", population: 12952218, cities: ["Kigali", "Butare", "Gisenyi"] },
    { name: "Burundi", capital: "Gitega", population: 11890784, cities: ["Gitega", "Bujumbura", "Ngozi"] },
    { name: "South Sudan", capital: "Juba", population: 10919573, cities: ["Juba", "Wau", "Malakal"] },
    { name: "Somalia", capital: "Mogadishu", population: 15893222, cities: ["Mogadishu", "Hargeisa", "Kismayo"] },
    { name: "Djibouti", capital: "Djibouti", population: 883560, cities: ["Djibouti", "Ali Sabieh", "Tadjourah"] },
    { name: "Eritrea", capital: "Asmara", population: 3546000, cities: ["Asmara", "Keren", "Massawa"] },
    { name: "Comoros", capital: "Moroni", population: 806153, cities: ["Moroni", "Moutsamoudou", "Mitsamiouli"] },
    { name: "Seychelles", capital: "Victoria", population: 98347, cities: ["Victoria", "Anse Boileau", "Beau Vallon"] },
    { name: "Mauritius", capital: "Port Louis", population: 1271768, cities: ["Port Louis", "Curepipe", "Vacoas"] },
    { name: "Cape Verde", capital: "Praia", population: 543767, cities: ["Praia", "Mindelo", "Santa Maria"] },
    { name: "Gambia", capital: "Banjul", population: 2416661, cities: ["Banjul", "Serrekunda", "Brikama"] },
    { name: "Senegal", capital: "Dakar", population: 16425864, cities: ["Dakar", "Touba", "Saint-Louis"] },
    { name: "Mali", capital: "Bamako", population: 20250833, cities: ["Bamako", "Sikasso", "Mopti"] },
    { name: "Niger", capital: "Niamey", population: 24206644, cities: ["Niamey", "Zinder", "Maradi"] },
    { name: "Chad", capital: "N'Djamena", population: 14497000, cities: ["N'Djamena", "Moundou", "Sarh"] }
]